import type { NextPage } from "next";
import Head from "next/head";
import Button from "../components/ui/button";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const buttonHandler = () => {
    console.log("Selam");
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Button onClick={buttonHandler}>Selam</Button>
      </div>
    </div>
  );
};

export default Home;
